FROM ubuntu:24.10

# 出力をソート・整形するためのperlライブラリのインストール
# メモリリーク検出のためのvalgrindのインストール
RUN apt-get update && apt-get install -y --no-install-recommends \
    libperl5.38 \
    valgrind \
    && rm -rf /var/lib/apt/lists/*

# ゲストユーザー(1002:1002)を作成
RUN groupadd -g 1002 guest && \
    useradd -m -s /bin/bash -u 1002 -g 1002 guestt

# watchdogをコピー
# uid:gid=root:rootで、ファイルのパーミッションは700にする
COPY watchdog /home/watchdog
RUN chown root:root /home/watchdog
RUN chmod 700 /home/watchdog

WORKDIR /home/guest
