FROM ubuntu:24.10

# 出力をソート・整形するためのperlライブラリのインストール
RUN apt-get update && apt-get install -y --no-install-recommends \
    libperl5.38 \
    && rm -rf /var/lib/apt/lists/*

RUN mkdir -p /home/guest
RUN chown -R 1000:1000 /home/guest
RUN chmod -R 755 /home/guest

WORKDIR /home/guest
